### ISSUE TITLE
Имена файлов для вывода в отладчике

### ISSUE THREAD

**Issue by j123123** [bmstu-iu9/simple-refal#116]
https://github.com/bmstu-iu9/simple-refal/blob/7c2000d7f221f7896d010d786581ed64ffeb9ef1/src/srlib/refalrts.cpp#L3308-L3321
использование функции sscanf в таком виде небезопасно. 
В спецификаторе формата для sscanf надо указать размер буфера. Например, см. https://stackoverflow.com/a/28183357

**Comment by j123123** [comment]
Размеры буферов ``line[cMaxLen]`` и ``filename[cMaxLen]`` одинаковы. Если функция ``fgets ()`` прочитает ``cMaxLen`` байт, ``sscanf ()`` запишет из буфера ``line`` в буфер ``filename``, добавляя при этом в начало ``" >> "`` и при этом произойдет переполнение стека. Возможный способ исправления : ``char filename[cMaxLen + 4] = {0}; ``

**Comment by j123123** [comment]
Хотя стоп, похоже что тут нет никаких выходов за границы... Это просто такой необычный способ проверить, две ли ``" >> "`` или одна ``" > "`` или вообще нет? И для этого надо делать sscanf из буфера в буфер? Какое-то странное решение

**Comment by Mazdaywik** [comment]
Вообще, отладчик был курсовым проектом Натальи Стрельниковой #49, и я ей предлагал весь пользовательский интерфейс описывать через `fgets()` + `sscanf()` (типа `sscanf(line, "trace %s >> %s", funcname, file) == 2`). Но она написала парсер немного иначе, из-за чего возникли такие непонятные места.

В будущем я как раз планирую переписать (#85) отладчик, и при этом ввод парсить в следующей манере:
```C++
if (
  sscanf(line, "%s %s > \"[^\"]\"", cmd, item, filename) == 3
  || sscanf(line, "%s %s > %s", cmd, item, filename) == 3
) {
  command(cmd, arg, "w", filename);
} else if (
  sscanf(line, "%s %s >> \"[^\"]\"", cmd, item, filename) == 3
  || sscanf(line, "%s %s >> %s", cmd, item, filename) == 3
) {
  command(cmd, arg, "a", filename);
} else if (sscanf(line, "%s %s", cmd, item) == 2 || sscanf(line, "%s %s", cmd, item) == 2) {
  command(cmd, arg);
  … … …
}
```
Понятно, что буфер будет выделяться с запасом, а именно, будет равен по длине входной строке. Но это потом как-нибудь, есть много другой приоритетной работы.

**Comment by Mazdaywik** [comment]
https://github.com/bmstu-iu9/simple-refal/blob/92e514db68c5c78122c77ff7ed6c1e4e33e06f43/SRLib/refalrts.cpp#L1491-L1499

https://github.com/bmstu-iu9/simple-refal/blob/92e514db68c5c78122c77ff7ed6c1e4e33e06f43/SRLib/refalrts.cpp#L1867-L1871

Не знал, что так можно вставлять куски листинга в комментарии.

**Comment by j123123** [comment]
>В будущем я как раз планирую переписать (#85) отладчик, и при этом ввод парсить в следующей манере:
...

Разумнее будет написать какой-нибудь конечный автомат, делается это достаточно просто. И да, если читать имя файла через ``%s``, файлы с пробелами и табами будут "неоткрываемыми"

**Comment by Mazdaywik** [comment]
Возвращаюсь к примерному листингу кода (в нём были две опечатки в самом интересном месте):
```C++
if (
  sscanf(line, "%s %s > \"%[^\"]\"", cmd, item, filename) == 3
  || sscanf(line, "%s %s > %s", cmd, item, filename) == 3
) {
```
Что значит `…\"%[^\"]\"…` внутри строки? Смотрим в документацию:
http://www.cplusplus.com/reference/cstdio/scanf/

specifier | Description | Characters extracted
-- | -- | --
…|…|…
[^characters] | Negated scanset | Any number of characters none of them specified as characters between the brackets.
…|…|…
Срабатывает как `%s`, только выбирает символы из указанного диапазона. Кстати, [работает](https://wandbox.org/permlink/eSY7tmPpS3vv0bdq).

Таким образом, если пользователь хочет указать имя файла с пробелом внутри, то пишет его в кавычках. В противном случае кавычки можно опустить.

В твоём же коммите, кстати, есть проблема. Функция `fgets()` после считывания строки в конец кладёт символ `\n`, который будет передан в функцию `fopen()`. Т.е. будет вызываться `fopen("log.txt\n", "w")`, что на Windows не сработает, а на Linux создаст файл с очень неудобным именем.

Другая проблема в недопонимании синтаксиса. В строке `" >> %s"` пробелы символизировали цепочку _незначащих_ пробелов. Напомню, в `scanf()` пробел означает любую последовательность пробельных символов, в том числе и пустую. А значит, следующие две команды являются допустимыми и эквивалентными (пробелы я обозначил значком `·`):
```
trace·FuncName>>log.txt
···trace···FuncName···>>····log.txt····
···trace···FuncName·>>····log.txt····
```
В первом и втором случае твой коммит код отвергнет, во втором случае имя файла будет `"   log.txt    \n"`.

Так что твой коммит вносит проблем больше, чем решает их. Я вынужден его откатить.

**Comment by j123123** [comment]
>Таким образом, если пользователь хочет указать имя файла с пробелом внутри, то пишет его в кавычках.

А как поступать, если имя файла содержит такие кавычки? По-моему возможностей sscanf тут недостаточно

> Так что твой коммит вносит проблем больше, чем решает их. Я вынужден его откатить.

Согласен. Тем не менее, некие проблемы с изначальным кодом с sscanf все же есть. Тут sscanf используется не чтобы что-то куда-то прочитать, а как некое средство паттерн-матчинга и "выцепливания" имени файла из строки. Мне кажется, тут правильней использовать ДКА (детерминированный конечный автомат), есть специальные инструменты для генерации подобных конечных автоматов. Можно например взять Flex, как раз в тему разработки компиляторов.

**Comment by j123123** [comment]
https://wandbox.org/permlink/zB5H3TDmYAXhu7Sm пока вот что-то такое придумал (см. функцию ``test_func3 ()``), могу попробовать довести до ума, добавить распознавание экранирований чтоб можно было использовать пробелы. Подход с использованием sscanf имеет свои ограничения

**Comment by Mazdaywik** [comment]
> А как поступать, если имя файла содержит такие кавычки?
А зачем вам такое имя файла? На Windows, к слову, знак двойной кавычки в именах запрещён.

> …а как некое средство паттерн-матчинга и "выцепливания" имени файла из строки.
Именно так и предполагалось.

> Можно например взять Flex, как раз в тему разработки компиляторов.
Можно взять Flex, можно взять Bison, можно взять PCRE…

Для меня отладчик — настолько периферический инструмент, поэтому я в нём изначально не планировал реализовывать сложный анализ пользовательского ввода — планировал организовать простое чтение строки через `fgets()` и дальнейший его разбор путём сопоставления с несколькими образцами в `sscanf()`.

Отладчик появился в прошлом году только потому, что я счёл эту тему интересной для курсового проекта (и не ошибся: Дарье Сухомлиновой @StrixSeloputo писать отладчик понравилось). После этого я его использовал один или два раза (прежде всего из-за его ограниченности #85).

Кстати, [записка к курсовому](https://github.com/bmstu-iu9/simple-refal/blob/21756c5e224f8cb7c770159d86e203481f18e81b/doc/%D0%A0%D0%9F%D0%97_%D0%A1%D1%83%D1%85%D0%BE%D0%BC%D0%BB%D0%B8%D0%BD%D0%BE%D0%B2%D0%B0_%D0%9F%D0%BE%D1%88%D0%B0%D0%B3%D0%BE%D0%B2%D1%8B%D0%B9_%D0%BE%D1%82%D0%BB%D0%B0%D0%B4%D1%87%D0%B8%D0%BA.pdf).

Планируемый вариант с кавычками (для имён файлов с пробелами) неплох тем, что удовлетворяет принципу наименьшего удивления — именно так работают Bash и COMMAND.COM. То есть поведение знакомое, тем более, что знаки `>>` и `>` тоже взяты оттуда. Если пользователь по ошибке напишет:
```
trace FuncName >> C:\My Documents\log.txt
```
то получит файл `C:\My`. Не очень красиво.

> Подход с использованием sscanf имеет свои ограничения
Их достаточно. Общий формат команды, предполагаемый в задаче #85, будет иметь вид:
```
{ Mode ":" } Command Args [ (">" | ">>") Filename ]
```
При этом команды `print` и `trace` хотелось бы расширить до
```
print e.X t.Y $callee
trace Func1 Func2 Func3 >> log.txt
```
А это парсить `scanf`’ом очень неудобно. Так что парсер имеет смысл развивать.

> могу попробовать довести до ума, добавить распознавание экранирований чтоб можно было использовать пробелы.
В качестве символа экранирования нельзя будет использовать знак `\`, поскольку он используется в именах файлов Windows. А так, помощь и идеи приветствуются.

**Comment by j123123** [comment]
> А зачем вам такое имя файла? На Windows, к слову, знак двойной кавычки в именах запрещён.

Да, но в Linux например такого запрета нет. Подобные искуственные ограничения всегда раздражают. Например, тот же WATCOM компилятор надо устанавливать в пути (директории) без пробелов, иначе оно не находит путь (видимо тоже через sscanf что-то там читают :smile: )

>Для меня отладчик — настолько периферический инструмент, поэтому я в нём изначально не планировал реализовывать сложный анализ пользовательского ввода — планировал организовать простое чтение строки через ``fgets()`` и дальнейший его разбор путём сопоставления с несколькими образцами в ``sscanf()``.

Если так хочется это делать через сопоставления с образцом, то почему бы часть, отвечающую за разбор строки, не написать на Рефале? По-моему он для этого подходит намного лучше, чем Си с кучей ``sscanf()``, и выглядеть это будет элегантней.

Что же касается функций типа ``sscanf()`` c ``%s`` спецификатором, то они очень небезопасны т.к. не проверяют длину ввода, что часто приводит к появлению багов/уязвимостей с переполнением буфера, и об этом следует всегда говорить, тщательно следить за тем, что место, в которое мы что-то "сканируем" достаточно большое, чтобы не вылезти за границы и не попортить стек/хип. В общем я б не советовал студентов приучать использовать подобного рода функции, и всегда надо говорить об их потенциальной опасности.

>В качестве символа экранирования нельзя будет использовать знак \, поскольку он используется в именах файлов Windows

Поправка: знак ``\`` в Windows используется не в именах, а в путях к файлу. А для экранирования используется ``/``. С другой стороны, в линуксе ситуация прямо противоположная, т.е. ``\`` используется для экранирования, тогда как ``/`` это разделитель пути.

Для Windows список символов, которые запрещены к использованию в имени файла, можно посмотреть здесь: https://msdn.microsoft.com/ru-ru/library/c6bdca6y(v=vs.90).aspx
Для Linux: http://www.linuxcenter.ru/lib/books/kostromin/gl_04_01.phtml
Единственный символ, который нельзя использовать в имени файла ни там, ни там это ``/``, но в линуксе он используется как разделитель при задании пути к директории, так что он не годится.

Можно еще договориться, что если мы пишем ``\\`` то это означает что мы хотим написать ``\``, и тогда пути надо будет задавать как-то так: ``C:\\My\ Documents\\log.txt``

В общем что-то с этим надо попрбовать придумать. Жду предложений.

P.S. чтобы в комментарии на гитхабе текст ответа не слипался с текстом цитируемым через ``>``, надо сделать пустую строку между цитируемым текстом и ответом

**Comment by Mazdaywik** [comment]
> Да, но в Linux например такого запрета нет.  Подобные искуственные ограничения всегда раздражают.

Знаю про подход Linux: в именах допустимы все 254 символа ASCII кроме `/` и `\0`. И меня часто раздражает, что нельзя внутри имени файла использовать знак «/», типа «ввод/вывод.txt», «км/ч.txt» и т.д.

> Если так хочется это делать через сопоставления с образцом, то почему бы часть, отвечающую за разбор строки, не написать на Рефале? По-моему он для этого подходит намного лучше, чем Си с кучей sscanf(), и выглядеть это будет элегантней.

Элегантней ли? Во-первых, это писать на Рефале внутри рантайма самого Рефала, что архитектурно несколько странно. Исходник рантайма будет зависеть от скомпилированного файла на Рефале, что несколько запутает сборку.

Во-вторых, слишком толстым будет слой FFI: нужно будет сначала преобразовать строку в связный список, потом передать её функции на Рефале, а та должна свои результаты работы передать в рантайм обратно.

Лучше, ввиду ограниченности `sscanf` переписать в виде классического front-end’а: лексер + парсер контекстно-свободной грамматики рекурсивным спуском.

> Что же касается функций типа `sscanf()` c `%s` спецификатором, то они очень небезопасны т.к. не проверяют длину ввода, что часто приводит к появлению багов/уязвимостей с переполнением буфера…

У меня в коде предложен простой рецепт: длина исходной строки (читаемая `fread()`) ограничена размером буфера. Для полей `%s` выделяются буфера ровно такого же размера. Очевидно, что подстрока не может быть длиннее её строки. А вот `scanf()`/`fscanf()` без ограничения размера буфера действительно использовать опасно. Но у меня используется с ограничением (только что проверил и убедился).

> Поправка: знак `\` в Windows используется не в именах, а в путях к файлу. А для экранирования используется `/`. С другой стороны, в линуксе ситуация прямо противоположная, т.е. `\` используется для экранирования, тогда как `/` это разделитель пути.

Поправка поправки: в Windows в файловых операциях можно взаимозаменяемо использовать знаки `\` и `/`:
```C++
FILE *f = fopen("C:/Windows/system.ini", "rt");
```
совершенно правильно откроет файл. Это уже в командной строке нельзя использовать знак `/` в качестве разделителя, поскольку там он символизирует опции командной строки:
```
C:\Users\Mazdaywik\Documents\Simple Refal\src\srlib>dir c:/Windows
Ошибка в формате параметра: "Windows".

C:\Users\Mazdaywik\Documents\Simple Refal\src\srlib>dir /w/os
 Том в устройстве C не имеет метки.
 Серийный номер тома: 8E78-E4A9

 Содержимое папки C:\Users\Mazdaywik\Documents\Simple Refal\src\srlib

[.]                            [..]                           [common]
[platform-Windows]             [platform-unknown]             [platform-MINGW32]
[platform-Linux]               [platform-Darwin]              [platform-CYGWIN]
refalrts.rasl                  refalrts-platform-specific.h   LICENSE
make.sh                        make.bat                       Hash.sref
LibraryEx.sref                 GetOpt.sref                    refalrts.h
Library.sref                   refalrts.cpp
              11 файлов        226 176 байт
               9 папок  908 947 435 520 байт свободно
```
В Linux экранировать имена нужно прежде всего в оболочке, чтобы она их не спутывала со своими управляющими символами (типа тех же `*`). Если язык программирования позволяет писать строки без экранирования, то и экранировать ничего не надо:
```Python
f = open("""file
with
strange\name""", "w")
```
Получится файл с именем (в нотации Си): `"file\nwith\nstrange\\name"`.

> Можно еще договориться, что если мы пишем `\\` то это означает что мы хотим написать `\`, и тогда пути надо будет задавать как-то так: `C:\\My\ Documents\\log.txt`

Фу, какая гадость. Именно этих `\\` я и хочу избежать.

> В общем что-то с этим надо попрбовать придумать. Жду предложений.

Варианты:
* Те же двойные (или одинарные) кавычки, две кавычки подряд символизируют одну кавычку. Пример: `"abc""def'ghi"` и `'abc"def''ghi'` обозначают одну и ту же строку.
* Любой текст, после `>>` или `>` до конца строки считается именем файла за исключением пробельных символов в начале или конце (`·` — пробел, `→` — табуляция).
```
trace··FuncName···>>···out.txt→··
trace·OtherFunc··>>·→·→·C:\My·documents\out.txt···
```
Именами открытых файлов ожидаемо будут `out.txt` и `C:\My·documents\out.txt`.

А вообще, нужно будет реализовывать полноценные лексический и синтаксический анализаторы. Чтобы можно было писать что-то вроде:
```
trace ParseStatement(t.SymTable t.NextToken) UpdateTable ( e.Key e.Value s.Scope ) NextToken >> C:\Simple Refal\dump.txt
```
В дамп выводим вместо всего вызова функции `ParseStatement` только значения двух указанных переменных (если они определены), аналогично для `UpdateTable` (только там три переменных). А вот вызов `NextToken` дампим целиком.

> P.S. чтобы в комментарии на гитхабе текст ответа не слипался с текстом цитируемым через `>`, надо сделать пустую строку между цитируемым текстом и ответом

Спасибо, поправил предыдущий комментарий.

**Comment by j123123** [comment]
>- Tе же двойные (или одинарные) кавычки, две кавычки подряд символизируют одну кавычку. Пример: ``"abc""def'ghi"`` и ``'abc"def''ghi'`` обозначают одну и ту же строку.
>- Любой текст, после >> или > до конца строки считается именем файла за исключением пробельных символов в начале или конце (· — пробел, → — табуляция).

Со вторым вариантом будет проблема в том, что нельзя будет указать на файл, имя которого начинается с пробела или табуляции, не указывая полный путь.
С первым и вторым вариантом будет проблема в том, что никак нельзя указать на файл, если имя его или путь к нему содержит newline.

Мое предложение следующее:
1. читаем 0 или больше пробелов
1. читаем (распознаем) одну или две ``>``. Если не распознали то ``return stdout;`` 
1. читаем 0 или больше пробелов
1. смотрим что за символ нам попался в самом начале
   1. Если в самом начале ``"``, остаток строки обрабатываем все следующим образом:
      1. Если видим символ отличный от ``"`` то его следует понимать как часть имени файла или пути
      1. Если видим ``"`` и следующий символ это тоже ``"`` то это надо понимать как один символ ``"`` в имени файла или пути
      1. Если следующий за ``"`` символ это ``n``, ``t``... в общем надо обрабатывать это в точности таким же образом, как эскейп-последовательность в Си, с той лишь разницей, что вместо ``\`` используется ``"``: https://en.wikipedia.org/wiki/Escape_sequences_in_C#Table_of_escape_sequences 
      1. Если следующий за ``"`` символ это таб, пробел, newline или нулевой байт, следует это понимать как конец строки
      1. Если следующий за ``"`` символ это что-то, что не попадает в пункты .b .c .d, делаем ``return stdout;``
   1. Если в самом начале что-либо отличное от ``"``, следует считать все символы частью пути, пока не дойдем до нулевого байта или newline. Минус такого подхода - нельзя указать имя файла,  начинающегося с пробела или таба(не указывая к нему полный путь) и нельзя указать на файл, если в имени и/или пути есть newline

Если возражений нет, могу в ближайшие дни попробовать реализовать что-то такое.

**Comment by Mazdaywik** [comment]
> Со вторым вариантом будет проблема в том, что нельзя будет указать на файл, имя которого начинается с пробела или табуляции, не указывая полный путь.
> С первым и вторым вариантом будет проблема в том, что никак нельзя указать на файл, если имя его или путь к нему содержит newline.

Плохо представляю себе сценарий, когда может потребоваться создавать отладочный дамп с таким странным именем. Но пускай будет в качестве пасхалки своего рода.

> i. Если в самом начале `"`, остаток строки обрабатываем следующим образом:

Этот пункт одобряю полностью.

> ii. Если в самом начале что-либо отличное от `"`, следует считать все символы частью пути, пока не дойдем до нулевого байта или newline. Минус такого подхода - нельзя указать имя файла, начинающегося с пробела или таба(не указывая к нему полный путь) и нельзя указать на файл, если в имени и/или пути есть newline

Предлагаю для случаев без кавычек обрезать пробельные символы с обоих концов. Ведь для того, чтобы указать имена файлов с пробелами в начале или конце, есть кавычки.

> Если возражений нет, могу в ближайшие дни попробовать реализовать что-то такое.

Буду рад, если сделаете.
