### ISSUE TITLE
#ifdef вставки в код и отступы

### ISSUE THREAD

**Issue by j123123** [bmstu-iu9/simple-refal#120]
В некоторых местах в коде, например тут:
https://github.com/bmstu-iu9/simple-refal/blob/658f035caf460b6b9c290ae2a106809c6bbe68b2/src/srlib/refalrts.cpp#L4780-L4795
есть ``#ifdef`` вставки, которые нарушают отступы в коде. Возможно, имеет смысл переписать подобные фрагменты как-нибудь так:
````C++
       case icPerformNative: 
         { 
           #ifdef ENABLE_DEBUGGER 
           if (debugger.handle_function_call(begin, end, callee) == cExit) { 
             return cExit; 
           } 
           #endif  // ifdef ENABLE_DEBUGGER 
           RefalNativeFunction *native_callee = 
             static_cast<RefalNativeFunction*>(callee); 
           FnResult res = (native_callee->ptr)(begin, end); 
           if (res != cSuccess) { 
             return res; 
           } 
} 
````
или так
````C++
       case icPerformNative: 
         { 
           #ifdef ENABLE_DEBUGGER 
             if (debugger.handle_function_call(begin, end, callee) == cExit) { 
               return cExit; 
             } 
           #endif  // ifdef ENABLE_DEBUGGER 
           RefalNativeFunction *native_callee = 
             static_cast<RefalNativeFunction*>(callee); 
           FnResult res = (native_callee->ptr)(begin, end); 
           if (res != cSuccess) { 
             return res; 
           } 
} 
````
, добавив соответствующие правила в [рекомендации по стилю оформления](https://github.com/bmstu-iu9/simple-refal/blob/master/doc/style-guide.md) ?

**Comment by Mazdaywik** [comment]
Вставки не нарушают отступы в коде, они намеренно так записаны. Директивы условной компиляции работают с кодом как с последовательностью строк и как бы «нарезают» его в зависимости от настроек.

Отступы в коде отражают синтаксическую структуру кода на Си++: появился уровень вложенности — появился новый отступ. А директивы препроцессора плевать хотели на синтаксическую структуру.

Надуманный пример:
```C++
#ifdef FOO
  if (foo > 0) {
#else
  for (i = 0; i < bar; ++i) {
#endif
    …
    …
  }
```

Не помню где, но в каком-то коде, реально работающем (может студенческом, может и нет) видел такую вещь:
```C++
int some_array[] = {
#include "array_content.h"
};
```

Поэтому, чтобы подчеркнуть факт того, что код «нарезается», директивы препроцессора пишутся без отступов, они как бы «врезаются» в обычный код на Си++.

> В некоторых местах в коде, например тут:

Это должно быть так _во всех_ местах. Если есть место, где написано иначе, то там надо исправить.

> добавив соответствующие правила в [рекомендации по стилю оформления](https://github.com/bmstu-iu9/simple-refal/blob/master/doc/style-guide.md) ?

Наоборот в «Рекомендациях по стилю» зафиксировал используемый подход.
