### ISSUE TITLE
Протестировать получение пути к текущему файлу на OS X

### ISSUE THREAD

**Issue by Mazdaywik** [bmstu-iu9/simple-refal#82]
Эта задача — подзадача для #77.

## Задача
Необходимо протестировать возможность определения пути к текущему исполнимому файлу на платформе OS X. Дело в том, что `argv[0]` может врать. Например, при запуске программы, находящейся в `$PATH` в нём может быть только имя файла без полного пути; искусственным запуском `exec(…)` можно вообще установить произвольное значение.

Следует опробовать функции `_NSGetExecutablePath()` и `proc_pidpath()` на предмет того, на сколько они дают полезный вывод.

Кроме того, следует проверить общую правильность работы компилятора на OS X, в частности, правильное определение системно-зависимых файлов по `uname`.

### 1. Склонировать репозиторий Простого Рефала
```
$ cd ~
$ git clone https://github.com/bmstu-iu9/simple-refal
```
**Ожидаемый результат:** в домашней папке должна появиться папка `simple-refal`
### 2. Переключиться на ветку `experimental-osx-my-name`
```
$ cd simple-refal
$ git checkout experimental-osx-my-name
$ ls -l
```
**Ожидаемый результат:** в папке помимо других папок и файлов должна появиться папка `osx-my-name-test`.
### 3. Собрать компилятор Простого Рефала:
```
$ ./bootstrap.sh
$ ls -l bin/*
```
Процесс может занять до 10-15 минут в зависимости от процессора и используемого компилятора C++ (Clang немного быстрее, GCC немного медленнее). Сначала будет произведена раскрутка самого компилятора, потом запустятся автоматические тесты (они как раз и требуют уйму времени). Есть тесты, проверяющие ошибочные ситуации — при их выполнении выводятся сообщения типа `Ok! This failure normal and expected` — не надо пугаться, так и должно быть.

**Ожидаемый результат:** на консоль будет выписано много текста, последней строкой должно быть `**** ALL TESTS PASSED ****`, в папке `bin` должны появиться исполнимые файлы `srefc`, `srefc-core`, `srmake`, `srmake-core` и несколько других.

### 4. Собрать тестовую программу
```
$ cd osx-my-name-test
$ ../bin/srmake test.sref
$ ls -l
```
**Ожидаемый результат:** компиляция должна пройти успешно, в папке должен появиться исполнимый файл с именем `test` (а также несколько файлов с расширениями `*.cpp` и `*.rasl`).

### 5. Запустить тестовую программу

Запуск из текущей папки:
```
$ ./test
```
Запуск на уровень выше:
```
$ mkdir subdir && cd subdir
$ ../test
```
Запуск на уровень ниже:
```
$ cd ../..
$ osx-my-name-test/test
```
Запуск из каталога PATH:
```
cd ~
set PATH=~/simple-refal/osx-my-name-test:$PATH
test
```
**Ожидаемый результат:** ни в одном из трёх запусков не вылезало сообщение об ошибке (строка, начинающаяся с `ERROR:`).

Вывод всех трёх запусков нужно скопировать и добавить в комментарии (или написать мне на почту).

**Comment by ilyailya** [comment]
# Тест 1

Запуск `$ ./test`

Вывод:

~~~bash
**DEBUG: my name is ./test**
_NSGetExecutablePath result: /Users/Ilya/dev/simple-refal/osx-my-name-test/./test
_NSGetExecutablePath + realpath: /Users/Ilya/dev/simple-refal/osx-my-name-test/test
cModuleNameBufferLen 1025
PROC_PIDPATHINFO_MAXSIZE 4096
proc 5230: /Users/Ilya/dev/simple-refal/osx-my-name-test/test
Native time: 0.000 seconds (100.0 %).

Total program time: 0.000 seconds (100.0 %).
Step count 2
Memory used 3 nodes, 3 * 32 = 96 bytes
Identifiers allocated: 0
~~~

# Тест 2

Запуск :

~~~
$ mkdir subdir && cd subdir

$ ../test
~~~

Вывод:

~~~
**DEBUG: my name is ../test**
_NSGetExecutablePath result: /Users/Ilya/dev/simple-refal/osx-my-name-test/subdir/../test
_NSGetExecutablePath + realpath: /Users/Ilya/dev/simple-refal/osx-my-name-test/test
cModuleNameBufferLen 1025
PROC_PIDPATHINFO_MAXSIZE 4096
proc 5289: /Users/Ilya/dev/simple-refal/osx-my-name-test/test
Native time: 0.000 seconds (100.0 %).

Total program time: 0.000 seconds (100.0 %).
Step count 2
Memory used 3 nodes, 3 * 32 = 96 bytes
Identifiers allocated: 0

~~~

# Тест 3

Запуск:

~~~
$ cd ../..
$ osx-my-name-test/test
~~~

Вывод:

~~~
**DEBUG: my name is osx-my-name-test/test**
_NSGetExecutablePath result: /Users/Ilya/dev/simple-refal/osx-my-name-test/test
_NSGetExecutablePath + realpath: /Users/Ilya/dev/simple-refal/osx-my-name-test/test
cModuleNameBufferLen 1025
PROC_PIDPATHINFO_MAXSIZE 4096
proc 5321: /Users/Ilya/dev/simple-refal/osx-my-name-test/test
Native time: 0.000 seconds (100.0 %).

Total program time: 0.000 seconds (100.0 %).
Step count 2
Memory used 3 nodes, 3 * 32 = 96 bytes
Identifiers allocated: 0
~~~

# Тест 4
Замечание: В macOS не работает способ установки переменной $PATH через set. Поэтому я поменял переменную в .bash_profile
`export PATH=~/dev/simple-refal/osx-my-name-test:$PATH
`

После этого переменная $PATH выглядит следующим образом `/Users/Ilya/dev/simple-refal/osx-my-name-test:/Users...`


Запуск: 

~~~
$ cd ~
$ test
~~~

Вывод пустой

Я попробовал сделать файл исполняемыем с помощью `chmod +x test`, но это не принесло никаких результатов

**Comment by Mazdaywik** [comment]
@ilyailya, я забыл, что `test` — встроенная команда Bash, при вызове без параметров она ничего не выводит. Попробуйте переименовать тестовую программу, например, в `test-path` и повторить четвёртый тест.

**Comment by ilyailya** [comment]
Переименовал и после этого выполнил 
~~~
$ cd ~
$ test-path 
~~~

Вывод:

~~~
**DEBUG: my name is test-path**
_NSGetExecutablePath result: /Users/Ilya/dev/simple-refal/osx-my-name-test/test-path
_NSGetExecutablePath + realpath: /Users/Ilya/dev/simple-refal/osx-my-name-test/test-path
cModuleNameBufferLen 1025
PROC_PIDPATHINFO_MAXSIZE 4096
proc 6350: /Users/Ilya/dev/simple-refal/osx-my-name-test/test-path
Native time: 0.000 seconds (100.0 %).

Total program time: 0.000 seconds (100.0 %).
Step count 2
Memory used 3 nodes, 3 * 32 = 96 bytes
Identifiers allocated: 0
~~~

**Comment by Mazdaywik** [comment]
Как я и предполагал, если программа находится в PATH, то в `argv[0]` будет находиться имя без пути.

Функция `_NSGetExecutablePath()` возвращает «неочищенный» путь, `proc_pidpath()` (второй тест) — сразу «очищенный». Обе функции одинаково пригодны для своей цели (поскольку результат передаётся в `fopen`).
