### ISSUE TITLE
Некорректное обобщение двух атомов

### ISSUE THREAD

**Issue by MrSmail** [bmstu-iu9/simple-refal#83]
**Описание:** при использовании -OP, 2 предложения, которые начинаются с 'a' обобщаются до s.$ ...
**Шаги для воспроизведения:**
$ git checkout master
$ git pull
$ ./bootstrap.sh
$ echo -e "\$ENTRY Go {\n  'a' 'b' e.Any ('c') = ;\n  'a' 'd' e.Any ('e') = ;\n}" > test_opt.sref

> Это тест:
> $ENTRY Go {
>   'a' 'b' e.Any ('c') = ;
>   'a' 'd' e.Any ('e') = ;
> }
> 

$ ./bin/srefc-core test_opt.sref -OP
$ cat test_opt.cpp | grep -m 1 -A 1 "FAST GEN"
**Ожидаемый результат:** 
      //FAST GEN: 'a' s.$ e.$ ( s.$ )
      //GLOBAL GEN: 'a' s.$ e.$ ( s.$ )
**Полученный результат:** 
      //FAST GEN: s.$ s.$ e.$ ( s.$ )
      //GLOBAL GEN: s.$ s.$ e.$ ( s.$ )

> Аналогичный результат для чисел и идентификаторов. Проверял так:

$ echo -e "\$ENTRY Go {\n  13 'b' e.Any ('c') = ;\n  13 'd' e.Any ('e') = ;\n}" > test_opt.sref
$ echo -e "\$ENTRY Go {\n  #Ident 'b' e.Any ('c') = ;\n  #Ident 'd' e.Any ('e') = ;\n}" > test_opt.sref

**Comment by Mazdaywik** [comment]
Последний рабочий коммит — c72c7eb1dd004009dfa3798014c62dc265b17bd9 — 8 июня 2016.
Следующий за ним коммит, который не проходит — a4c25d450aeedb078ef45d47b37af04c0f6c8809 — 19 июня 2016.
Сам Скрыпников и сломал оптимизацию, исправляя в ней ошибку.

**Comment by MrSmail** [comment]
В коде master в FastGen.sref::FastGen-Terms отсутствует обобщение на случай равенства атомов. Добавим перед случаем, где атомы могут иметь отличные значения:
>  s.Num
>  ((#Atom e.val)) ((#Atom e.val)) = (#Atom e.val);

>  s.Num
>  ((#Atom e.val1))
>  ((#Atom e.val2)) =
>    (#S '$'
>      (( (#Atom e.val1) ))
>      (( (#Atom e.val2) ))
>    );

Проверим ручным тестирование на описанных ранее случаях:
$ echo -e "$ENTRY Go {\n 'a' 'b' e.Any ('c') = ;\n 'a' 'd' e.Any ('e') = ;\n}" > test_opt.sref
$ ./bin/srefc-core test_opt.sref -OP
$ cat test_opt.cpp | grep -m 1 -A 1 "FAST GEN"
>      //FAST GEN: 'a' s.$ e.$ ( s.$ )
>      //GLOBAL GEN: 'a' s.$ e.$ ( s.$ )

$ echo -e "$ENTRY Go {\n 13 'b' e.Any ('c') = ;\n 13 'd' e.Any ('e') = ;\n}" > test_opt.sref
$ ./bin/srefc-core test_opt.sref -OP
$ cat test_opt.cpp | grep -m 1 -A 1 "FAST GEN"
>      //FAST GEN: 13 s.$ e.$ ( s.$ )
>      //GLOBAL GEN: 13 s.$ e.$ ( s.$ )

$ echo -e "$ENTRY Go {\n #Ident 'b' e.Any ('c') = ;\n #Ident 'd' e.Any ('e') = ;\n}" > test_opt.sref
$ ./bin/srefc-core test_opt.sref -OP
$ cat test_opt.cpp | grep -m 1 -A 1 "FAST GEN"
>      //FAST GEN: # Ident s.$ e.$ ( s.$ )
>      //GLOBAL GEN: # Ident s.$ e.$ ( s.$ )

Кажется, что этой правки достаточно для разрешения проблемы.

**Comment by Mazdaywik** [comment]
Мне тоже так показалось, но автотесты начинают вылетать. Пока не разбирался, почему. В ветке [bug-83](../commits/bug-83) лежит коммит с этой правкой, но он не работает (падает один из тестов `opt-pattern-?.sref`).
